"""Regenerate the source-inventory block of docs/METHODOLOGY.md from source_registry.

Dry-run by default. It prints the diff and changes nothing without --write.

Three guarantees:

  * Only rows with publish_github = true are emitted. A confidential source
    never reaches generated output.
  * Content is written only between the sentinel comments. Everything else in
    the file — the standing rules, the architecture section, the key
    calculations — is byte-identical afterwards, and that is asserted rather
    than assumed.
  * A null renders as an em dash. Never an empty cell, never an invented value.

The "18 Gov Sources" map badge lives in index.html and is not touched by this
script at all.

Usage:
    python scripts/generate_methodology.py                    # dry run
    python scripts/generate_methodology.py --write            # apply
    python scripts/generate_methodology.py --write --init-sentinels
"""
import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _db import get_conn  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

# Windows consoles default to cp1252; this output contains em dashes and
# arrows lifted verbatim from the documentation.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BEGIN = "<!-- BEGIN GENERATED SOURCE INVENTORY -->"
END = "<!-- END GENERATED SOURCE INVENTORY -->"

DASH = "—"


def halt(msg):
    sys.exit(f"HALT: {msg}")


def find_methodology():
    for cand in (REPO / "docs" / "METHODOLOGY.md",
                 REPO / "ONS_Population_Estimates" / "docs" / "METHODOLOGY.md"):
        if cand.exists():
            return cand
    halt("docs/METHODOLOGY.md not found")


def cell(value):
    if value is None:
        return DASH
    text = str(value).strip()
    if not text:
        return DASH
    return text.replace("|", "\\|")


def fetch_rows(cur):
    cur.execute("""
        SELECT source_code, source_name, metrics, publisher, cadence,
               publication_window, refresh_tier, status
        FROM source_registry
        WHERE publish_github = true
        ORDER BY (regexp_match(source_code, '^\\d+'))[1]::int, source_code
    """)
    return cur.fetchall()


def frequency_label(cadence, window):
    """The Frequency cell, rendered from the two columns that carry it.

    The register's own Frequency text mixes both — "Annual (late January)" is
    a cadence and a window in one cell. Reassembling it that way keeps the
    generated column readable and comparable against the original.

    Two cases avoid manufacturing noise. 'periodic' is a vocabulary token
    rather than a description, so where a window exists it speaks for itself:
    "Decennial" beats "Periodic (Decennial)". And where the window already
    opens with the cadence, wrapping it repeats the word — "Quarterly
    (Quarterly, roughly 8 weeks after quarter end)" — so the window is used
    alone.
    """
    if not cadence:
        return window or None
    label = cadence.capitalize()
    if not window:
        return label
    if cadence == "periodic":
        return window
    if window.lower().startswith(cadence.lower()):
        return window
    return f"{label} ({window})"


def build_block(rows):
    lines = [
        BEGIN,
        "",
        "<!-- Generated by scripts/generate_methodology.py from the",
        "     source_registry table. Do not hand-edit: run the script.",
        "     Confidential sources are excluded by publish_github.",
        "     Column order matches the register this block replaced, because",
        "     scripts/register_lib.py parses it positionally. -->",
        "",
        "| S# | Source | Metric(s) | Publisher | Frequency | Tier | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for code, name, metrics, publisher, cadence, window, tier, status in rows:
        metric_text = ", ".join(metrics) if metrics else None
        lines.append(
            f"| {cell(code)} | {cell(name)} | {cell(metric_text)} | "
            f"{cell(publisher)} | {cell(frequency_label(cadence, window))} | "
            f"{cell(tier)} | {cell(status)} |")
    lines += [
        "",
        f"{len(rows)} published sources. **Tier** is assigned by acquisition "
        "mechanics, not importance: A is a stable machine-readable endpoint "
        "safe to ingest unattended, B is landing-page discovery with gated "
        "ingestion, C is manual only. An em dash means the field is not "
        "documented in this repository; the open list is in "
        "[SOURCE_REGISTRY_GAPS.md](SOURCE_REGISTRY_GAPS.md).",
        "",
        END,
    ]
    return "\n".join(lines)


def compare_against_register(before, rows):
    """Report every cell the generated block would change, field by field.

    The Metric(s) question is settled — source_registry now carries it. This
    exists so the remaining differences, which are mostly Frequency wording,
    are visible as a list rather than buried in a whole-file diff.
    """
    span = locate_existing_table(before)
    if span is None:
        return []
    start, end = span
    lines = before.splitlines()[start:end]
    old = {}
    for line in lines:
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 5 or set(cells[0]) <= set("-: ") or cells[0] == "S#":
            continue
        old[cells[0]] = {"source": cells[1], "metrics": cells[2],
                         "publisher": cells[3], "frequency": cells[4]}

    diffs = []
    for code, name, metrics, publisher, cadence, window, _, _ in rows:
        o = old.get(code)
        if not o:
            diffs.append((code, "row", "(absent from the register)", name))
            continue
        new = {"source": name,
               "metrics": ", ".join(metrics) if metrics else DASH,
               "publisher": publisher,
               "frequency": frequency_label(cadence, window) or DASH}
        for field in ("source", "metrics", "publisher", "frequency"):
            if o[field] != new[field]:
                diffs.append((code, field, o[field], new[field],
                              classify(o[field], new[field])))
    return diffs


def classify(was, now):
    """Say what kind of difference this is, so the review can be triaged.

    A separator change is not a content change, and an added detail is not a
    loss. Only the last class needs a decision before the first write.
    """
    def norm(s):
        for ch in "();":
            s = s.replace(ch, "," if ch == ";" else " ")
        return " ".join(s.lower().replace(" ,", ",").split())

    a, b = norm(was), norm(now)
    if a == b:
        return "punctuation only - content identical"
    if a in b:
        return "enrichment - register text retained, detail added"
    if b in a:
        return "LOSS - the register said more than the registry holds"
    return "changed - review both"


def locate_existing_table(text):
    """Line span of the hand-written register table, header row included."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith("| S# | Source |"):
            start = i
            break
    if start is None:
        return None
    end = start
    while end < len(lines) and lines[end].startswith("|"):
        end += 1
    return start, end


def splice(text, block, init_sentinels):
    """Return the candidate file content, and how the block was placed."""
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail, "replaced existing sentinel block"

    if not init_sentinels:
        return None, ("sentinels absent — the generated block has nowhere to "
                      "go without a placement decision")

    span = locate_existing_table(text)
    if span is None:
        return None, "sentinels absent and the register table was not found"
    start, end = span
    lines = text.splitlines(keepends=True)
    candidate = "".join(lines[:start]) + block + "\n" + "".join(lines[end:])
    return candidate, ("sentinels inserted around the hand-written register "
                       f"table at lines {start + 1}-{end}")


def assert_outside_unchanged(before, after):
    """Everything outside the sentinel region must be byte-identical."""
    def outside(text):
        if BEGIN not in text or END not in text:
            return None
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head, tail

    a, b = outside(before), outside(after)
    if a is None:
        return  # first insertion; nothing to compare against
    if a != b:
        halt("content outside the sentinel block would change. Refusing to "
             "write — this script only owns the generated block.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="apply the change (default is dry run)")
    ap.add_argument("--init-sentinels", action="store_true",
                    help="allow inserting the sentinels for the first time, "
                         "around the existing hand-written register table")
    args = ap.parse_args()

    path = find_methodology()
    before = path.read_text(encoding="utf-8")

    conn = get_conn()
    cur = conn.cursor()
    rows = fetch_rows(cur)
    cur.execute("SELECT COUNT(*) FROM source_registry WHERE publish_github = false")
    withheld = cur.fetchone()[0]
    cur.close()
    conn.close()

    block = build_block(rows)
    after, how = splice(before, block, args.init_sentinels)

    print(f"file            : {path}")
    print(f"rows emitted    : {len(rows)}")
    print(f"rows withheld   : {withheld} (publish_github = false)")
    print(f"placement       : {how}")
    print()

    if after is None:
        print("DRY RUN — nothing to diff yet.")
        print()
        print("docs/METHODOLOGY.md carries no sentinel comments, so this "
              "script has no block it owns. Re-run with --init-sentinels to "
              "see the diff that would place them around the existing "
              "register table.")
        print()
        print("Generated block that would be written:")
        print()
        print(block)
        return 0

    # Cell-level report of what the block would change, so the residual
    # differences are a reviewable list rather than a wall of diff.
    cell_diffs = compare_against_register(before, rows)
    if cell_diffs:
        buckets = {}
        for d in cell_diffs:
            buckets.setdefault(d[4], []).append(d)
        print(f"CELL-LEVEL CHANGES AGAINST THE HAND-WRITTEN REGISTER "
              f"({len(cell_diffs)})")
        for kind in sorted(buckets, key=lambda k: (not k.startswith("LOSS"), k)):
            print(f"\n  [{kind}]  x{len(buckets[kind])}")
            for code, field, was, now, _ in buckets[kind]:
                print(f"    S{code} {field}")
                print(f"      was: {was}")
                print(f"      now: {now}")
        losses = [d for d in cell_diffs if d[4].startswith("LOSS")]
        print()
        print(f"  Needs a decision before the first write: {len(losses)}")
        print()
    else:
        print("No cell-level change: every Source, Metric(s), Publisher and "
              "Frequency value reproduces the hand-written register exactly.")
        print()

    diff = list(difflib.unified_diff(
        before.splitlines(keepends=True), after.splitlines(keepends=True),
        fromfile=f"a/{path.name}", tofile=f"b/{path.name}"))
    if not diff:
        print("No change — the generated block matches the file.")
        return 0

    print("".join(diff))

    if not args.write:
        print()
        print("DRY RUN — nothing written. Re-run with --write to apply.")
        return 0

    assert_outside_unchanged(before, after)
    path.write_text(after, encoding="utf-8")
    print()
    print(f"WROTE {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
