"""Generate the README source table from the METHODOLOGY register.

README was right about S19's wiring status and METHODOLOGY was wrong, which
is evidence about which document gets maintained — and METHODOLOGY has since
been designated the register. Two hand-maintained descriptions of the same
facts will diverge again, and next time the contradiction test would not know
which to believe. So README's source table is now generated from
METHODOLOGY plus the live database, inside a marked block.

  python scripts/sync_readme_sources.py           rewrite the block
  python scripts/sync_readme_sources.py --check   exit non-zero if stale

`--check` is what makes this enforceable rather than merely available.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from register_lib import (  # noqa: E402
    PUBLISH, map_layer_fields, parse_register, register_sort_key,
    source_for_signal_column)
from _db import get_conn  # noqa: E402

README = PUBLISH / "docs" / "README.md"
BEGIN = "<!-- BEGIN generated:sources -->"
END = "<!-- END generated:sources -->"


def build_block():
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("""
        SELECT column_name FROM information_schema.columns
         WHERE table_name = 'staging_la_signals' ORDER BY ordinal_position
    """)
    signal_cols = [r[0] for r in cur.fetchall()]
    conn.close()

    register = parse_register()

    wired = {}
    for col in signal_cols:
        s = source_for_signal_column(col)
        if s:
            wired.setdefault(s, []).append(col)

    layered = {}
    for f in map_layer_fields():
        s = source_for_signal_column(f, allow_non_signal=True)
        if s:
            layered.setdefault(s, []).append(f)

    L = [BEGIN,
         "",
         "<!-- Generated by scripts/sync_readme_sources.py from",
         "     docs/METHODOLOGY.md (the source register) and the live",
         "     database. Do not hand-edit: run the script instead.",
         "     `--check` fails the build if this block is stale. -->",
         "",
         "| S# | Source | Metric(s) | In signals JSON | Map layer |",
         "| --- | --- | --- | --- | --- |"]
    for s in sorted(register, key=register_sort_key):
        r = register[s]
        w = "yes" if s in wired else "no"
        lay = layered.get(s)
        ltxt = "yes" if lay else "no"
        L.append(f"| {s} | {r['source']} | {r['metrics']} | {w} | {ltxt} |")
    L += ["",
          "**In signals JSON** means the source populates "
          "`staging_la_signals` and reaches "
          "`data/signals/staging_la_signals_latest.json`. **Map layer** means "
          "`index.html` renders it as a choropleth. They are different "
          "states: S19 PIP is in the signals JSON with no map layer, and S15 "
          "house prices are a map layer fed by their own "
          "`hpi_la_prices.json` with no signals column. A source that is "
          "\"no\" in both columns is loaded in Postgres and queryable there.",
          "",
          END]
    return "\n".join(L)


def main():
    check_only = "--check" in sys.argv
    text = README.read_text(encoding="utf-8")
    block = build_block()

    if BEGIN in text and END in text:
        current = text[text.index(BEGIN):text.index(END) + len(END)]
        if current == block:
            print("README source table is in sync with METHODOLOGY.")
            return 0
        if check_only:
            print("README source table is STALE against docs/METHODOLOGY.md.")
            print("Run: python scripts/sync_readme_sources.py")
            return 1
        text = text.replace(current, block)
    else:
        if check_only:
            print("README has no generated:sources block.")
            return 1
        sys.exit("HALT: README has no generated:sources block. Add the "
                 f"markers {BEGIN} / {END} around the source table first.")

    README.write_text(text, encoding="utf-8")
    print(f"rewrote the generated:sources block in "
          f"{README.relative_to(PUBLISH.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
